import 'cypress-file-upload';

describe('suite Crear_Producto', () => {

    it('verificar que al crear un producto sin imagen el mensaje se "No subiste ninguna imagen..."', () =>{
        cy.visit("http://micromarket.shopbarrio.online/")
        cy.xpath("/html/body/div/div/html/body/nav/div/div/ul/li[2]/a/a/i").click()
        cy.wait(3000)
        cy.get('#producto').type("Cereal Fitnes")
        cy.wait(3000)
        cy.get('#select_categorias').select('Abarrotes')
        cy.wait(3000)
        cy.get('#marca').type("Nestle")
        cy.wait(3000)
        cy.get('#precio').type("23.00")
        cy.wait(3000)
        cy.get('#descripcion').type("Un buen producto alimenticio")
        cy.wait(3000)
        cy.get('#guardarP').click()
        cy.wait(3000)
        cy.get('#swal2-html-container').contains("No subiste ninguna imagen...")
        cy.wait(3000)
    })
    /*it('verificar que el archivo de fixture exista antes de subirlo', () => {
        cy.task('countFiles', 'cypress/downloads').then((count) => {})
      });*/
    it('verificar que al crear un producto ya existente de el mensaje se "Oopss"', () =>{
        cy.visit("http://micromarket.shopbarrio.online/")
        cy.wait(3000)
        cy.xpath("/html/body/div/div/html/body/nav/div/div/ul/li[2]/a/a/i").click()
        cy.wait(3000)
        cy.get('#producto').type("Cereal Fitness nuevo3")
        cy.wait(3000)
        cy.get('#select_categorias').select('Abarrotes')
        cy.wait(3000)
        cy.get('#marca').type("Nestle")
        cy.wait(3000)
        cy.get('#precio').type("23.00")
        cy.wait(3000)
        cy.get('#descripcion').type("Un buen producto alimenticio")
        cy.wait(3000)
        cy.get('#img-uploader').attachFile('cerealFitness.png')
        cy.wait(3000)
        cy.reload()
        cy.get('#producto').type("Cereal Fitness nuevo3")
        cy.wait(3000)
        cy.get('#select_categorias').select('Abarrotes')
        cy.wait(3000)
        cy.get('#marca').type("Nestle")
        cy.wait(3000)
        cy.get('#precio').type("23.00")
        cy.wait(3000)
        cy.get('#descripcion').type("Un buen producto alimenticio")
        cy.wait(3000)
        cy.get('#img-uploader').attachFile('cerealFitness.png')
        cy.wait(5000)
        cy.get('#guardarP').click()
        cy.wait(3000)
        cy.get('#swal2-title').contains("¡Genial!")
    })
    
})
